version: "3.8"
services:
  vscode:
    build: .
    image: rust-env
    container_name: rust-env
    hostname: rust-env
    volumes:
      - ..:/workspace
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - $HOME/.gitconfig:/root/.gitconfig
      - rust-bash-history:/root/.history
      - rust-vscode-extensions:/root/.vscode-server/extensions
      - rust-vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
    working_dir: /workspace
    entrypoint: /bin/bash

volumes:
  rust-bash-history:
  rust-vscode-extensions:
  rust-vscode-extensions-insiders: